"""table Product

Revision ID: 142d928bf75c
Revises: 1e819acd0093
Create Date: 2020-07-08 21:38:09.092396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d928bf75c'
down_revision = '1e819acd0093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('name', name=op.f('uq_product_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
