"""table Variant

Revision ID: 2165f0b71d4f
Revises: 53f5d0b8e2ce
Create Date: 2020-07-09 11:43:49.290876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2165f0b71d4f'
down_revision = '53f5d0b8e2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_modificator', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.String(length=40), nullable=True),
    sa.Column('update_date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    # ### end Alembic commands ###
