"""table Product new fields

Revision ID: 505e758fa527
Revises: fac5640f59a8
Create Date: 2020-07-09 11:09:11.231713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505e758fa527'
down_revision = 'fac5640f59a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('banner', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'banner')
    # ### end Alembic commands ###
