"""table Product new fields

Revision ID: 53f5d0b8e2ce
Revises: 505e758fa527
Create Date: 2020-07-09 11:17:42.195870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f5d0b8e2ce'
down_revision = '505e758fa527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cutout', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cutout')
    # ### end Alembic commands ###
