"""table Product new fields

Revision ID: c91eec73baa1
Revises: fc452d63ec86
Create Date: 2020-07-08 22:09:58.766906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91eec73baa1'
down_revision = 'fc452d63ec86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('create_date', sa.String(length=40), nullable=True))
    op.add_column('product', sa.Column('update_date', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'update_date')
    op.drop_column('product', 'create_date')
    # ### end Alembic commands ###
