"""table Variant new fields

Revision ID: f81a078eeae4
Revises: 2165f0b71d4f
Create Date: 2020-07-09 12:20:00.692552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81a078eeae4'
down_revision = '2165f0b71d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_variant_product_id_product'), 'variant', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_variant_product_id_product'), 'variant', type_='foreignkey')
    op.drop_column('variant', 'product_id')
    # ### end Alembic commands ###
