"""table Product new fields

Revision ID: fc452d63ec86
Revises: 142d928bf75c
Create Date: 2020-07-08 21:41:18.334823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc452d63ec86'
down_revision = '142d928bf75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('inventory', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('short_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'short_description')
    op.drop_column('product', 'base_price')
    op.drop_column('product', 'inventory')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
